(var sum 0)
(var first 1)
(var second 2)
(while (< second 4000000)
    ((set second (+ first second))
    (set first (- second first))
    (if (= second (* 2 (/ second 2)))
        (set sum (+ sum second))))
)